"""
VISTA — Train ResNet-50 face classifier from facial_pipeline_results.npz
=========================================================================
Loads the pre-built .npz (generated by regenerate_npz.py), performs a
correct stratified split on ORIGINAL images only, appends augmented
variants to the train split, then fine-tunes ResNet-50 for both:

    Split A : 80 % train / 10 % val / 10 % test
    Split B : 70 % train / 15 % val / 15 % test

Key correctness guarantee
--------------------------
The .npz stores 30 augmented variants per original image.  Each variant
carries metadata["augmentation_index"] in 0-29.  We split on the SET of
unique (student, source_image) pairs drawn ONLY from originals, then add
all 30 aug variants for every source image that ended up in train.
Val and test contain ONLY augmentation_index == 0 samples (one per
original image, identity-preserving crop with no stochastic transform
applied at index 0).  An assertion verifies zero leakage before training.

Outputs  (training_results/)
-----------------------------
    best_model_npz_splitA.pth
    best_model_npz_splitB.pth
    results_npz_splitA.txt
    results_npz_splitB.txt
    confusion_matrix_npz_splitA.png
    confusion_matrix_npz_splitB.png
    training_curve_npz_splitA.png
    training_curve_npz_splitB.png
    data_split_npz_log.txt

Usage:
    python train_from_npz.py [--split A|B|both] [--epochs N]
"""

from __future__ import annotations

import argparse
import copy
import logging
import sys
import time
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.models import ResNet50_Weights, resnet50

# ── UTF-8 console fix (Windows CP1252) ───────────────────────────────────────
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────────────
_ROOT       = Path(__file__).resolve().parent
NPZ_PATH    = _ROOT / "data" / "processed" / "facial_pipeline_results.npz"
RESULTS_DIR = _ROOT / "training_results"

# ── Constants ────────────────────────────────────────────────────────────────
NUM_CLASSES    = 21
IMG_SIZE       = 112        # ArcFace-standard resize for training
BATCH_SIZE     = 32
EPOCHS         = 30
PATIENCE       = 7
LR             = 1e-4
SEED           = 42

# Discovered dynamically from .npz labels at load time — filled in load_npz()
KNOWN_USNS: list[str] = []
USN_TO_IDX: dict[str, int] = {}

SPLIT_CONFIGS = {
    "A": {"train": 0.80, "val": 0.10, "test": 0.10, "tag": "npz_splitA"},
    "B": {"train": 0.70, "val": 0.15, "test": 0.15, "tag": "npz_splitB"},
}


# ── Reproducibility ───────────────────────────────────────────────────────────
def seed_all(seed: int = SEED) -> None:
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark     = False


# ═══════════════════════════════════════════════════════════════════════════
# STAGE 1 — Load .npz
# ═══════════════════════════════════════════════════════════════════════════
def load_npz(path: Path) -> dict:
    """
    Load the .npz and return a flat dict with numpy arrays plus a structured
    per-sample record list for splitting.

    Also populates the module-level KNOWN_USNS, USN_TO_IDX, NUM_CLASSES
    from the actual label set in the file.
    """
    global KNOWN_USNS, USN_TO_IDX, NUM_CLASSES

    logger.info(f"Loading .npz from {path} ...")
    if not path.exists():
        raise FileNotFoundError(
            f"NPZ not found: {path}\n"
            f"Run regenerate_npz.py first."
        )

    data     = np.load(path, allow_pickle=True)
    images   = data["images"]       # (N,160,160,3) uint8
    embs     = data["embeddings"]   # (N,512) float32
    labels   = data["labels"]       # (N,) object → str
    metadata = data["metadata"]     # (N,) object → dict

    N = images.shape[0]
    logger.info(f"  images     {images.shape}  {images.dtype}")
    logger.info(f"  embeddings {embs.shape}  {embs.dtype}")
    logger.info(f"  labels     {labels.shape}  {labels.dtype}")
    logger.info(f"  metadata   {metadata.shape}  {metadata.dtype}")
    logger.info(f"  Total samples: {N:,}")

    # Build class list from actual labels in the file (sorted for determinism)
    unique_usns = sorted(set(str(l).strip("'\"") for l in labels))
    KNOWN_USNS  = unique_usns
    USN_TO_IDX  = {usn: i for i, usn in enumerate(KNOWN_USNS)}
    NUM_CLASSES = len(KNOWN_USNS)
    logger.info(f"  Classes discovered: {NUM_CLASSES} — {KNOWN_USNS}")

    records = []
    for i in range(N):
        usn    = str(labels[i]).strip("'\"")
        meta   = metadata[i]
        if hasattr(meta, 'item'):
            meta = meta.item()
        records.append({
            "idx":     i,
            "usn":     usn,
            "cls":     USN_TO_IDX.get(usn, -1),
            "source":  str(meta.get("source_image", "")),
            "aug_idx": int(meta.get("augmentation_index", 0)),
        })

    unknown = [r for r in records if r["cls"] == -1]
    if unknown:
        bad = {r["usn"] for r in unknown}
        logger.warning(f"Unknown USNs: {bad} ({len(unknown)} samples excluded)")

    return {
        "images":     images,
        "embeddings": embs,
        "labels":     labels,
        "metadata":   metadata,
        "records":    records,
    }


# ═══════════════════════════════════════════════════════════════════════════
# STAGE 2 — Splitting
# ═══════════════════════════════════════════════════════════════════════════
def split_npz(
    records: list[dict],
    train_ratio: float,
    val_ratio:   float,
    seed: int = SEED,
) -> tuple[list[int], list[int], list[int]]:
    """
    Correct stratified split that works on SOURCE IMAGES (not samples).

    1. Collect unique (usn, source_image) pairs — these represent original photos.
    2. Split those pairs into train/val/test by ratio.
    3. train  → indices of ALL 30 aug variants from train-assigned source images.
       val    → indices where aug_idx == 0 from val-assigned source images.
       test   → indices where aug_idx == 0 from test-assigned source images.

    This guarantees:
      - val and test contain only clean (unaugmented) original crops.
      - aug variants ONLY appear in train.
      - No data leakage between splits.

    Returns:
        train_indices, val_indices, test_indices  (lists of .npz row indices)
    """
    # Group by (usn, source_image)
    source_groups: dict[tuple[str,str], list[dict]] = defaultdict(list)
    for r in records:
        if r["cls"] == -1:
            continue
        source_groups[(r["usn"], r["source"])].append(r)

    # Build a list of unique sources with their class label
    sources = sorted(source_groups.keys())           # deterministic order
    source_labels = [USN_TO_IDX[s[0]] for s in sources]

    test_ratio = round(1.0 - train_ratio - val_ratio, 6)

    # First cut: carve off test
    if test_ratio > 0:
        src_trainval, src_test, _, _ = train_test_split(
            sources, source_labels,
            test_size=test_ratio,
            stratify=source_labels,
            random_state=seed,
        )
    else:
        src_trainval, src_test = sources, []

    # Second cut: carve off val from trainval
    if val_ratio > 0 and len(src_trainval) > 1:
        tv_labels = [USN_TO_IDX[s[0]] for s in src_trainval]
        val_fraction = val_ratio / (train_ratio + val_ratio)
        src_train, src_val, _, _ = train_test_split(
            src_trainval, tv_labels,
            test_size=val_fraction,
            stratify=tv_labels,
            random_state=seed,
        )
    else:
        src_train, src_val = src_trainval, []

    src_train_set = set(src_train)
    src_val_set   = set(src_val)
    src_test_set  = set(src_test)

    # Map source keys to indices
    train_indices: list[int] = []
    val_indices:   list[int] = []
    test_indices:  list[int] = []

    for key, group in source_groups.items():
        if key in src_train_set:
            # All 30 aug variants go into train
            for r in group:
                train_indices.append(r["idx"])
        elif key in src_val_set:
            # Only aug_idx == 0 (original crop, no stochastic transform) in val
            for r in group:
                if r["aug_idx"] == 0:
                    val_indices.append(r["idx"])
        elif key in src_test_set:
            # Only aug_idx == 0 in test
            for r in group:
                if r["aug_idx"] == 0:
                    test_indices.append(r["idx"])

    return train_indices, val_indices, test_indices


def assert_no_leakage(
    train_idx: list[int],
    val_idx:   list[int],
    test_idx:  list[int],
    records:   list[dict],
    tag: str,
) -> None:
    """Assert train/val/test index sets are disjoint and val/test have aug_idx==0 only."""
    tr_set = set(train_idx)
    va_set = set(val_idx)
    te_set = set(test_idx)

    # Disjoint
    assert not tr_set & va_set, f"[{tag}] LEAKAGE: {len(tr_set & va_set)} indices in both train and val"
    assert not tr_set & te_set, f"[{tag}] LEAKAGE: {len(tr_set & te_set)} indices in both train and test"
    assert not va_set & te_set, f"[{tag}] LEAKAGE: {len(va_set & te_set)} indices in both val and test"

    # Val and test must be aug_idx==0 only
    rec_map = {r["idx"]: r for r in records}
    bad_val  = [i for i in val_idx  if rec_map[i]["aug_idx"] != 0]
    bad_test = [i for i in test_idx if rec_map[i]["aug_idx"] != 0]
    assert not bad_val,  f"[{tag}] Val contains {len(bad_val)} augmented samples (aug_idx != 0)"
    assert not bad_test, f"[{tag}] Test contains {len(bad_test)} augmented samples (aug_idx != 0)"

    logger.info(f"[{tag}] Leakage check PASSED — train/val/test disjoint, val/test are originals-only.")


def print_class_dist(
    train_idx: list[int],
    val_idx:   list[int],
    test_idx:  list[int],
    records:   list[dict],
    tag: str,
) -> None:
    rec_map = {r["idx"]: r for r in records}
    tr_cnt = defaultdict(int)
    va_cnt = defaultdict(int)
    te_cnt = defaultdict(int)
    for i in train_idx: tr_cnt[rec_map[i]["cls"]] += 1
    for i in val_idx:   va_cnt[rec_map[i]["cls"]] += 1
    for i in test_idx:  te_cnt[rec_map[i]["cls"]] += 1

    header = f"\n[{tag}] CLASS DISTRIBUTION"
    lines  = [header,
              f"  {'USN':<20} {'TRAIN':>8} {'VAL':>6} {'TEST':>6}",
              "  " + "-" * 44]
    for cls, usn in enumerate(KNOWN_USNS):
        lines.append(f"  {usn:<20} {tr_cnt[cls]:>8} {va_cnt[cls]:>6} {te_cnt[cls]:>6}")
    lines.append("  " + "-" * 44)
    lines.append(
        f"  {'TOTAL':<20} {sum(tr_cnt.values()):>8} "
        f"{sum(va_cnt.values()):>6} {sum(te_cnt.values()):>6}"
    )
    logger.info("\n".join(lines))

    # Warn thin test classes
    thin = [(KNOWN_USNS[c], n) for c, n in te_cnt.items() if n < 3]
    for usn, n in thin:
        logger.warning(f"[{tag}] WARNING: {usn} has only {n} test sample(s) — metrics will be noisy.")


# ═══════════════════════════════════════════════════════════════════════════
# STAGE 3 — Dataset & DataLoaders
# ═══════════════════════════════════════════════════════════════════════════
class NPZFaceDataset(Dataset):
    """
    Serves (image_tensor, class_idx) pairs from pre-loaded numpy arrays.
    Images are (160,160,3) uint8 RGB — resized to 112x112 for the model.
    """
    def __init__(
        self,
        images:   np.ndarray,    # (N,160,160,3) uint8
        indices:  list[int],
        records:  list[dict],
        transform,
    ):
        self.images    = images
        self.indices   = indices
        self.rec_map   = {r["idx"]: r for r in records}
        self.transform = transform

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, pos: int):
        idx   = self.indices[pos]
        label = self.rec_map[idx]["cls"]
        img   = self.images[idx]           # (160,160,3) uint8 RGB

        # Resize 160→112 (ArcFace training standard)
        img_112 = Image.fromarray(img).resize((112, 112), Image.BILINEAR)
        tensor  = self.transform(img_112)
        return tensor, label


def build_transforms(is_train: bool):
    mean = [0.5, 0.5, 0.5]
    std  = [0.5, 0.5, 0.5]
    if is_train:
        return transforms.Compose([
            transforms.RandomHorizontalFlip(p=0.3),
            transforms.ColorJitter(brightness=0.15, contrast=0.15),
            transforms.ToTensor(),
            transforms.Normalize(mean, std),
        ])
    return transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])


def make_loaders(
    images: np.ndarray,
    train_idx: list[int],
    val_idx:   list[int],
    test_idx:  list[int],
    records:   list[dict],
    batch_size: int = BATCH_SIZE,
):
    tr_ds  = NPZFaceDataset(images, train_idx, records, build_transforms(True))
    va_ds  = NPZFaceDataset(images, val_idx,   records, build_transforms(False))
    te_ds  = NPZFaceDataset(images, test_idx,  records, build_transforms(False))
    kwargs = dict(num_workers=0, pin_memory=False)
    return (
        DataLoader(tr_ds, batch_size=batch_size, shuffle=True,  **kwargs),
        DataLoader(va_ds, batch_size=batch_size, shuffle=False, **kwargs),
        DataLoader(te_ds, batch_size=batch_size, shuffle=False, **kwargs),
    )


# ═══════════════════════════════════════════════════════════════════════════
# STAGE 4 — Model
# ═══════════════════════════════════════════════════════════════════════════
class ResNet50FaceClassifier(nn.Module):
    """
    ResNet-50 (ImageNet init) fine-tuned for 21-class face identification.
    Frozen: conv1, bn1, layer1, layer2
    Trainable: layer3, layer4, classification head
    Input: 112x112 RGB, mean=0.5 std=0.5
    """
    def __init__(self, num_classes: int = NUM_CLASSES):
        super().__init__()
        bb = resnet50(weights=ResNet50_Weights.IMAGENET1K_V1)
        for p in bb.parameters():
            p.requires_grad = False
        for layer in (bb.layer3, bb.layer4, bb.bn1):
            for p in layer.parameters():
                p.requires_grad = True

        self.features = nn.Sequential(
            bb.conv1, bb.bn1, bb.relu, bb.maxpool,
            bb.layer1, bb.layer2, bb.layer3, bb.layer4,
            bb.avgpool,
        )
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.BatchNorm1d(2048),
            nn.ReLU(inplace=True),
            nn.Dropout(0.4),
            nn.Linear(2048, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.3),
            nn.Linear(512, num_classes),
        )
        for p in self.head.parameters():
            p.requires_grad = True

    def forward(self, x):
        return self.head(self.features(x))

    def trainable_params(self):
        return [p for p in self.parameters() if p.requires_grad]

    def n_trainable(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    def n_frozen(self):
        return sum(p.numel() for p in self.parameters() if not p.requires_grad)


# ═══════════════════════════════════════════════════════════════════════════
# STAGE 5 — Train / Evaluate
# ═══════════════════════════════════════════════════════════════════════════
def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    total_loss = correct = total = 0
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        out  = model(imgs)
        loss = criterion(out, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * imgs.size(0)
        correct    += (out.argmax(1) == labels).sum().item()
        total      += imgs.size(0)
    return total_loss / max(total, 1), correct / max(total, 1)


@torch.no_grad()
def eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = correct = total = 0
    all_true, all_pred = [], []
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        out  = model(imgs)
        loss = criterion(out, labels)
        total_loss += loss.item() * imgs.size(0)
        preds       = out.argmax(1)
        correct    += (preds == labels).sum().item()
        total      += imgs.size(0)
        all_true.extend(labels.cpu().tolist())
        all_pred.extend(preds.cpu().tolist())
    return (
        total_loss / max(total, 1),
        correct    / max(total, 1),
        all_true, all_pred,
    )


# ═══════════════════════════════════════════════════════════════════════════
# STAGE 6 — Full split run
# ═══════════════════════════════════════════════════════════════════════════
def run_split(split_key: str, npz: dict, device: torch.device, epochs: int) -> None:
    cfg = SPLIT_CONFIGS[split_key]
    tag = cfg["tag"]
    seed_all(SEED)

    logger.info("\n" + "=" * 65)
    logger.info(
        f"  SPLIT {split_key}  "
        f"({int(cfg['train']*100)}/{int(cfg['val']*100)}/{int(cfg['test']*100)})"
    )
    logger.info("=" * 65)

    records = npz["records"]

    # Split on source images
    train_idx, val_idx, test_idx = split_npz(
        records, cfg["train"], cfg["val"], seed=SEED
    )

    # Assertions
    assert_no_leakage(train_idx, val_idx, test_idx, records, tag)

    # All classes in train
    tr_cls = {records[i]["cls"] for i in [records.index(r) for r in records if r["idx"] in set(train_idx)]}
    # faster lookup:
    idx_to_rec = {r["idx"]: r for r in records}
    tr_cls = {idx_to_rec[i]["cls"] for i in train_idx}
    missing = set(range(NUM_CLASSES)) - tr_cls
    assert not missing, f"[{tag}] Missing classes in train: {[KNOWN_USNS[c] for c in missing]}"
    logger.info(f"[{tag}] All {NUM_CLASSES} classes present in train.")

    print_class_dist(train_idx, val_idx, test_idx, records, tag)

    # Log split to file
    _write_split_log(train_idx, val_idx, test_idx, records, tag)

    # DataLoaders
    tr_loader, va_loader, te_loader = make_loaders(
        npz["images"], train_idx, val_idx, test_idx, records
    )
    logger.info(
        f"[{tag}] Loaders — "
        f"train batches={len(tr_loader)}  "
        f"val batches={len(va_loader)}  "
        f"test batches={len(te_loader)}"
    )

    # Model
    model     = ResNet50FaceClassifier(NUM_CLASSES).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.trainable_params(), lr=LR)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", factor=0.5, patience=4
    )
    logger.info(
        f"[{tag}] Model — trainable: {model.n_trainable():,}  "
        f"frozen: {model.n_frozen():,}"
    )

    # Training loop
    history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}
    best_val_acc = -1.0
    best_state   = None
    patience_cnt = 0
    best_epoch   = 0

    for epoch in range(1, epochs + 1):
        t0 = time.time()
        tr_loss, tr_acc = train_epoch(model, tr_loader, criterion, optimizer, device)
        va_loss, va_acc, _, _ = eval_epoch(model, va_loader, criterion, device)
        scheduler.step(va_acc)

        history["train_loss"].append(tr_loss)
        history["train_acc"].append(tr_acc)
        history["val_loss"].append(va_loss)
        history["val_acc"].append(va_acc)

        flag = ""
        if va_acc > best_val_acc:
            best_val_acc = va_acc
            best_state   = copy.deepcopy(model.state_dict())
            patience_cnt = 0
            best_epoch   = epoch
            flag         = "  ** best"

        else:
            patience_cnt += 1

        logger.info(
            f"[{tag}] Epoch {epoch:03d}/{epochs}  "
            f"tr_loss={tr_loss:.4f}  tr_acc={tr_acc:.4f}  "
            f"vl_loss={va_loss:.4f}  vl_acc={va_acc:.4f}  "
            f"({time.time()-t0:.0f}s){flag}"
        )

        if patience_cnt >= PATIENCE:
            logger.info(
                f"[{tag}] Early stop at epoch {epoch}. "
                f"Best epoch {best_epoch} val_acc={best_val_acc:.4f}"
            )
            break

    # Save best model
    ckpt = RESULTS_DIR / f"best_model_{tag}.pth"
    torch.save({
        "epoch": best_epoch,
        "val_acc": best_val_acc,
        "model_state_dict": best_state,
        "class_names": KNOWN_USNS,
        "split": split_key,
    }, ckpt)
    logger.info(f"[{tag}] Checkpoint saved: {ckpt}")

    # ── Test evaluation (touched once) ───────────────────────────────────────
    model.load_state_dict(best_state)
    _, test_acc, test_true, test_pred = eval_epoch(
        model, te_loader, criterion, device
    )
    logger.info(f"[{tag}] TEST ACCURACY = {test_acc:.4f}")

    final_tr_acc = history["train_acc"][-1]
    gap = abs(final_tr_acc - test_acc)
    overfit_msg = ""
    if gap > 0.15:
        overfit_msg = (
            f"\nOVERFITTING WARNING: train/test gap = {gap*100:.1f}% (>15%)\n"
            f"  Final train acc = {final_tr_acc:.4f}  test acc = {test_acc:.4f}"
        )
        logger.warning(overfit_msg)

    # Per-class accuracy
    per_cls_correct = defaultdict(int)
    per_cls_total   = defaultdict(int)
    for t, p in zip(test_true, test_pred):
        per_cls_total[t]   += 1
        if t == p:
            per_cls_correct[t] += 1
    per_cls_lines = []
    for c, usn in enumerate(KNOWN_USNS):
        tot = per_cls_total[c]
        cor = per_cls_correct[c]
        acc = cor / tot if tot else float("nan")
        per_cls_lines.append(f"  {usn} (class {c:02d}): {cor}/{tot} = {acc:.4f}")

    clf_rep = classification_report(
        test_true, test_pred,
        target_names=KNOWN_USNS, digits=4, zero_division=0,
    )

    # Confusion matrix
    cm = confusion_matrix(test_true, test_pred, labels=list(range(NUM_CLASSES)))
    _save_confusion_matrix(cm, tag)

    # Training curves
    _save_training_curve(history, tag)

    # Results text
    _write_results(
        tag=tag, split_key=split_key, cfg=cfg,
        best_epoch=best_epoch, best_val_acc=best_val_acc,
        test_acc=test_acc, final_tr_acc=final_tr_acc,
        gap=gap, overfit_msg=overfit_msg,
        per_cls_lines=per_cls_lines, clf_rep=clf_rep,
        history=history,
        train_size=len(train_idx),
        val_size=len(val_idx),
        test_size=len(test_idx),
        epochs_run=len(history["train_loss"]),
    )

    logger.info(f"[{tag}] DONE. All outputs in {RESULTS_DIR}")


# ═══════════════════════════════════════════════════════════════════════════
# Helpers — save plots + reports
# ═══════════════════════════════════════════════════════════════════════════
def _save_confusion_matrix(cm: np.ndarray, tag: str) -> None:
    fig, ax = plt.subplots(figsize=(14, 12))
    im = ax.imshow(cm, cmap=plt.cm.Blues, interpolation="nearest")
    plt.colorbar(im, ax=ax)
    ticks      = np.arange(NUM_CLASSES)
    short      = [u[-5:] for u in KNOWN_USNS]
    ax.set_xticks(ticks); ax.set_xticklabels(short, rotation=45, ha="right", fontsize=8)
    ax.set_yticks(ticks); ax.set_yticklabels(short, fontsize=8)
    thresh = cm.max() / 2.0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, str(cm[i, j]), ha="center", va="center",
                    fontsize=7, color="white" if cm[i,j] > thresh else "black")
    ax.set_xlabel("Predicted"); ax.set_ylabel("True")
    ax.set_title(f"Confusion Matrix — {tag} (Test Set)", fontsize=13)
    plt.tight_layout()
    out = RESULTS_DIR / f"confusion_matrix_{tag}.png"
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    logger.info(f"  Confusion matrix: {out}")


def _save_training_curve(history: dict, tag: str) -> None:
    epochs = list(range(1, len(history["train_loss"]) + 1))
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    ax1.plot(epochs, history["train_loss"], label="Train Loss", color="tab:blue")
    ax1.plot(epochs, history["val_loss"],   label="Val Loss",   color="tab:orange")
    ax1.set_xlabel("Epoch"); ax1.set_ylabel("Loss")
    ax1.set_title(f"Loss — {tag}"); ax1.legend(); ax1.grid(alpha=0.3)
    ax2.plot(epochs, [a*100 for a in history["train_acc"]], label="Train Acc", color="tab:blue")
    ax2.plot(epochs, [a*100 for a in history["val_acc"]],   label="Val Acc",   color="tab:orange")
    ax2.set_xlabel("Epoch"); ax2.set_ylabel("Accuracy (%)")
    ax2.set_title(f"Accuracy — {tag}"); ax2.legend(); ax2.grid(alpha=0.3); ax2.set_ylim(0, 105)
    plt.suptitle(f"VISTA ResNet-50 Training Curves — {tag}", fontsize=13)
    plt.tight_layout()
    out = RESULTS_DIR / f"training_curve_{tag}.png"
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    logger.info(f"  Training curve: {out}")


def _write_split_log(
    train_idx: list[int],
    val_idx:   list[int],
    test_idx:  list[int],
    records:   list[dict],
    tag: str,
) -> None:
    log_path = RESULTS_DIR / "data_split_npz_log.txt"
    idx_to_rec = {r["idx"]: r for r in records}
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"\n{'='*65}\n")
        f.write(f"SPLIT {tag.upper()}  — {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"{'='*65}\n\n")
        for name, idxs in [("TRAIN", train_idx), ("VAL", val_idx), ("TEST", test_idx)]:
            f.write(f"--- {name} ({len(idxs)} samples) ---\n")
            for i in sorted(idxs):
                r = idx_to_rec[i]
                f.write(f"  [{r['usn']}]  {r['source']}  aug={r['aug_idx']}\n")
            f.write("\n")
    logger.info(f"  Split log appended: {log_path}")


def _write_results(
    tag, split_key, cfg,
    best_epoch, best_val_acc, test_acc, final_tr_acc,
    gap, overfit_msg, per_cls_lines, clf_rep, history,
    train_size, val_size, test_size, epochs_run,
) -> None:
    out = RESULTS_DIR / f"results_{tag}.txt"
    lines = [
        "=" * 65,
        "VISTA — ResNet-50 Face Classifier Results (trained from .npz)",
        "(backbone: ImageNet pretrained ResNet-50, ArcFace preprocessing)",
        f"Split {split_key}  ({int(cfg['train']*100)}/{int(cfg['val']*100)}/{int(cfg['test']*100)})",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "=" * 65, "",
        "DATA SOURCE",
        f"  NPZ: {NPZ_PATH}",
        f"  Train samples (all 30 aug variants): {train_size:,}",
        f"  Val  samples  (aug_idx==0 only)     : {val_size:,}",
        f"  Test samples  (aug_idx==0 only)     : {test_size:,}", "",
        "TRAINING CONFIG",
        f"  Epochs run         : {epochs_run}  (max {EPOCHS})",
        f"  Best epoch         : {best_epoch}",
        f"  Early stop patience: {PATIENCE}",
        f"  Batch size         : {BATCH_SIZE}",
        f"  Learning rate      : {LR}",
        f"  Optimizer          : Adam",
        f"  Loss               : CrossEntropyLoss",
        f"  Backbone           : ResNet-50 (ImageNet, NOT ArcFace ONNX)",
        f"  Input size         : 112x112, mean=0.5 std=0.5", "",
        "ACCURACY SUMMARY",
        f"  Best val accuracy  : {best_val_acc*100:.2f}%",
        f"  Final train acc    : {final_tr_acc*100:.2f}%",
        f"  Test accuracy      : {test_acc*100:.2f}%",
        f"  Train/Test gap     : {gap*100:.2f}%",
    ]
    if overfit_msg:
        lines.append(overfit_msg)
    lines += ["", "EPOCH LOG (train_loss | train_acc | val_loss | val_acc)", "-" * 60]
    for ep, (tl, ta, vl, va) in enumerate(zip(
        history["train_loss"], history["train_acc"],
        history["val_loss"],   history["val_acc"],
    ), 1):
        lines.append(f"  Epoch {ep:03d}:  {tl:.4f} | {ta:.4f} | {vl:.4f} | {va:.4f}")
    lines += ["", "PER-CLASS TEST ACCURACY", "-" * 60]
    lines += per_cls_lines
    lines += ["", "CLASSIFICATION REPORT", "-" * 60, clf_rep, "", "=" * 65, "END"]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logger.info(f"  Results written: {out}")


# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════
def main(splits: list[str], epochs: int) -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info("=" * 65)
    logger.info("  VISTA — Train from facial_pipeline_results.npz")
    logger.info(f"  NPZ    : {NPZ_PATH}")
    logger.info(f"  Device : {device}")
    logger.info(f"  Epochs : {epochs}")
    logger.info("=" * 65)

    npz = load_npz(NPZ_PATH)

    for split_key in splits:
        run_split(split_key, npz, device, epochs)

    logger.info("\n" + "=" * 65)
    logger.info("  ALL SPLITS COMPLETE")
    logger.info(f"  Outputs in: {RESULTS_DIR}")
    logger.info("=" * 65)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train ResNet-50 face classifier from .npz"
    )
    parser.add_argument(
        "--split", choices=["A", "B", "both"], default="both",
        help="Which split to run (default: both)",
    )
    parser.add_argument(
        "--epochs", type=int, default=EPOCHS,
        help=f"Max training epochs (default: {EPOCHS})",
    )
    args = parser.parse_args()
    main(
        splits=["A", "B"] if args.split == "both" else [args.split],
        epochs=args.epochs,
    )
